#!/bin/sh
#
# 
#

minlength=`git config prohibit-message.minlength`
if [ -z "$minlength" ]; then
    git config prohibit-message.minlength 3
    minlength=3
fi
prohibitword=`git config prohibit-message.word`

set -e

if test "$#" = 2
then
	topic="refs/heads/$2"
else
	topic=`git symbolic-ref HEAD` ||
	exit 0 ;
fi

# echo "rebasing $1 $topic"

branchroot=`git show-branch --sha1-name $1 $topic | tail -1 | sed 's/^.*\[\(.*\)\].*$/\1/g'`

# echo "$1 and $topic is branched from "

git log --pretty --format=oneline $1 ...$branchroot | sed 's/^[^ ]* //g' |\
while read line; do
    if [ ${#line} -lt ${minlength} ]; then
        echo "commit message at branch '$1' seems temporary message (shorter than ${minlength} characters)."
	echo "prohibit to rebase with temporary commit."
        exit 1
    fi
    if [ ! -z "${prohibitword}" ] && [ `echo $line | grep -c "$prohibitword"` -gt 0 ]; then
        echo "commit message at branch '$1' seems temporary message (include prohibit word)."
	echo "prohibit to rebase with temporary commit."
        exit 1
    fi
done


